# Generated by Django 6.0.1 on 2026-07-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_user_active_session_key_user_approved_device_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingloginrequest',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='pendingloginrequest',
            name='country',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
