# Generated by Django 6.0.1 on 2026-07-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_pendingloginrequest_city_pendingloginrequest_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Staff activity log', 'verbose_name_plural': 'Staff activity logs'},
        ),
        migrations.AlterModelOptions(
            name='pendingloginrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Staff login device', 'verbose_name_plural': 'Staff login devices'},
        ),
    ]
