# Generated by Django 6.0.1 on 2026-07-24 11:10

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Staff account',
                'verbose_name_plural': 'Staff accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
