# Generated by Django 6.0.1 on 2026-07-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_staffaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_plain_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
