# Generated by Django 6.0.1 on 2026-07-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_user_staff_plain_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingloginrequest',
            name='decided_via',
            field=models.CharField(blank=True, choices=[('telegram', 'Telegram'), ('admin', 'Admin Site'), ('expired', 'Expired'), ('known_device', 'Known device')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingloginrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('expired', 'Expired'), ('known', 'Known device (auto-login)')], db_index=True, default='pending', max_length=10),
        ),
    ]
